
package fr.orsys.calcul.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.1
 * Thu Nov 19 10:09:07 GMT+01:00 2020
 * Generated source version: 3.4.1
 */

@XmlRootElement(name = "ResponseEnvelope", namespace = "http://localhost:9000/CalculatriceService")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseEnvelope", namespace = "http://localhost:9000/CalculatriceService")

public class AddResponse {

    @XmlElement(name = "Result")
    private double Result;

    public double getResult() {
        return this.Result;
    }

    public void setResult(double newResult)  {
        this.Result = newResult;
    }

}

