
package fr.orsys.calcul.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.1
 * Thu Nov 19 10:09:07 GMT+01:00 2020
 * Generated source version: 3.4.1
 */

@XmlRootElement(name = "multiplier", namespace = "http://localhost:9000/CalculatriceService")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "multiplier", namespace = "http://localhost:9000/CalculatriceService", propOrder = {"arg0", "arg1"})

public class Multiplier {

    @XmlElement(name = "arg0")
    private double arg0;
    @XmlElement(name = "arg1")
    private double arg1;

    public double getArg0() {
        return this.arg0;
    }

    public void setArg0(double newArg0)  {
        this.arg0 = newArg0;
    }

    public double getArg1() {
        return this.arg1;
    }

    public void setArg1(double newArg1)  {
        this.arg1 = newArg1;
    }

}

